mybatis:
  # mybatis配置文件位置
  #  config-location: classpath:mybatis-config.xml
  # mybatis mapper文件位置
  mapperLocations: classpath:mapper/*.xml
  # java实体类所在包
  typeAliasesPackage: com.monoder.mymanga.entity

  typeHandlersPackage: com.monoder.mymanga.handler
# 输出日志
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:

  servlet:

    multipart:
      max-file-size: 15MB
      max-request-size: 150MB